[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version = "1.0.2"
version_files = [
    "Sources/Define/PackageGlobals.swift:version",
]
major_version_zero = false
